# Generated by Django 2.1.3 on 2018-11-20 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('run', models.CharField(help_text='Rut del Adoptante', max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Correo Electronico', max_length=254)),
                ('nombre', models.IntegerField(help_text='Nombre y Apellido')),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today, help_text='Fecha de Nacimiento')),
                ('telefono', models.IntegerField(help_text='Numero de Celular')),
                ('region', models.CharField(help_text='Region', max_length=100)),
                ('ciudad', models.CharField(help_text='Ciudad', max_length=100)),
                ('tipo_vivienda', models.CharField(choices=[('G', 'Casa con Patio Grande'), ('P', 'Casa con Patio Pequeño'), ('S', 'Casa sin patio'), ('D', 'Departamento')], default='Casa con Patio Grande', help_text='Tamaño de la Vivienda', max_length=1)),
            ],
        ),
    ]
