# Generated by Django 2.1.3 on 2018-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='nombre',
            field=models.CharField(help_text='Nombre y Apellido', max_length=100),
        ),
    ]
