# Generated by Django 2.1.3 on 2018-11-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptante', '0005_auto_20181120_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adoptante',
            new_name='Adopta',
        ),
    ]
